config/routes.rb
Rails.application.routes.draw do
  resources :artists
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
      @artist = Artist.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-sm">

        <% @artists.each do |artist|%>
        <div class="col-sm-3 d-inline-block">
          <div class="card p-2 m-1 mr-1">
            <img class="card-img-top" style="height: 250px;" src="<%= artist.image_url%>">
            <div class="card-body">
              <h5 class="card-title text-center"><%= artist.name %></h5>
              <%= link_to "Ver más",  artist_path(artist), class: "btn btn-primary col-12" %>
            </div>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/artists/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-sm-8">
      <h3><%= @artist.name %></h3>
      <hr>
      <% @artist.albums.each do |album|%>
        <div class="col-sm-3 d-inline-block">
          <div class="card p-2 m-1 mr-1">
            <img class="card-img-top" style="height: 100px;" src="<%= album.image_url%>">
            <div class="card-body p-1">
              <div class="card-title text-center"><%= album.name %></div>
              <div class="card-text"><%= album.released_at %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-sm-4">
      <img src="<%= @artist.image_url %>" class="img-thumbnail">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Real Music</a>
      <div class="navbar-nav">
        <%= link_to "Artistas", artists_path, class: "nav-item nav-link active" %>
        <a class="nav-item nav-link" href="#">Mi musica</a>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>